# Compose file with mongo server
version: '3'

services:
  mongo:
    image: mongo
    container_name: mongo_ten_mil
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root